</div><!-- End of #container -->
            
            <div id="footer">
                <div>
                    <div class="nav" id="sub-nav">
                        <ul>
                            <li><a href="#">Trang Chủ</a></li>
                            <li><a href="#">Quản Lý Câu Hỏi</a></li>
                            <li><a href="#">Đăng Nhập</a></li>
                            <li><a href="#">Tạo Tài Khoản</a></li>
                            <li><a href="#">Phòng Thi</a></li>
                        </ul>
                        
                        <ul>
                            <li><a>Copyright&copy;2011 </a></li>
                            <li><a href="#">Trắc nghiệm online</a></li>
                            <li><a href="#">Privacy Notice</a></li>
                            <li><a href="#">Conditions of Use</a></li>
                        </ul>
                    </div>
                </div>
            </div><!-- End of #footer -->
        </div><!-- End of #wrapper -->

    </body>
</html>
