<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="author" content="vo anh kiet" />
        <link href="css/style.css" rel="stylesheet" type="text/css" />
        <?php echo $this->title ?>
    </head>

    <body>
        <div id="wrapper">
            <div id="header">                            
                <div id="top-page">
                    <form action="" method="get" name="search">
                        <label>Tìm kiếm:</label><input id="txtSearch" type="text" name="search"/>
                        <input type="submit" value="Tìm" name="submit" id="btSearch" />
                    </form>
                </div><!-- End of #top-page -->
                <div id="logo">
                    <img src="images/logo.png" alt="logo"/>
                </div><!-- End of #logo -->
                <div id="banner">
                </div><!-- End of #banner -->
                
                <div id="main-nav" class="clear nav">
                    <div>
                        <ul>
                            <li><a href="#">Trang Chủ</a></li>
                            <li><a href="#">Quản Lý Câu Hỏi</a></li>
                            <li><a href="#">Đăng Nhập</a></li>
                            <li><a href="#">Tạo Tài Khoản</a></li>
                            <li><a href="#">Phòng Thi</a></li>
                        </ul>
                    </div>
                </div><!-- End of #main-nav -->
            </div><!-- End of #header -->
            
            <div id="container">